# Generated by Django 4.1 on 2022-10-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productreview",
            name="name",
        ),
    ]
