# Generated by Django 4.1 on 2022-10-12 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_item_category"),
        ("baseapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreview",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="cart.item",
            ),
        ),
    ]
