# Generated by Django 4.1 on 2022-09-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "baseapp",
            "0004_billingaddress_coupon_order_refund_payment_orderitem_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[("I", "Individual lesson"), ("G", "Group lesson")],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="label",
            field=models.CharField(
                choices=[("S", "Single lesson"), ("P", "Package of lessons")],
                max_length=5,
            ),
        ),
    ]
