# Generated by Django 4.1 on 2022-09-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0005_alter_item_category_alter_item_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField(max_length=1000)),
                (
                    "date_created",
                    models.DateField(auto_now_add=True, verbose_name="Created on date"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="item",
            name="label",
            field=models.CharField(
                choices=[("P", "Package of lessons"), ("S", "Single lesson")],
                max_length=5,
            ),
        ),
    ]
