# Generated by Django 4.1 on 2022-09-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0006_contact_alter_item_label"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[("G", "Group lesson"), ("I", "Individual lesson")],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="label",
            field=models.CharField(
                choices=[("S", "Single lesson"), ("P", "Package of lessons")],
                max_length=5,
            ),
        ),
    ]
