# Generated by Django 4.1 on 2022-09-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0007_delete_contact_alter_item_category_alter_item_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[("I", "Individual lesson"), ("G", "Group lesson")],
                max_length=5,
            ),
        ),
    ]
