# Generated by Django 4.1 on 2022-09-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0009_alter_item_category_alter_item_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="label",
            field=models.CharField(
                choices=[("S", "Single lesson"), ("P", "Package of lessons")],
                max_length=5,
            ),
        ),
    ]
