# Generated by Django 4.1 on 2022-09-25 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0017_alter_item_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="billing_address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="coupon",
        ),
        migrations.RemoveField(
            model_name="order",
            name="items",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="item",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="user",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="refund",
            name="order",
        ),
        migrations.DeleteModel(
            name="BillingAddress",
        ),
        migrations.DeleteModel(
            name="Coupon",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="Refund",
        ),
    ]
