# Generated by Django 4.1 on 2022-09-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[("C", "Course"), ("L", "Lesson")], max_length=5
            ),
        ),
    ]
