# Generated by Django 4.1 on 2022-09-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[("L", "Lesson"), ("C", "Course")], max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="label",
            field=models.CharField(
                choices=[("S", "Single lesson"), ("P", "Package of lessons")],
                max_length=5,
            ),
        ),
    ]
