# Generated by Django 4.1 on 2022-09-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_item_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="label",
            field=models.CharField(
                choices=[("P", "Package of lessons"), ("S", "Single lesson")],
                max_length=5,
            ),
        ),
    ]
