# Generated by Django 4.1 on 2022-09-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_alter_item_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[("L", "Lesson"), ("C", "Course")], max_length=5
            ),
        ),
    ]
